sonata_admin:
    title: Žaisk
    title_logo: images/zaisk_logo.svg
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            main:
                label: Pagrindinis
                keep_open: true
                items:
                    - admin.user
                    - admin.review
                    - admin.game

    options:
        legacy_twig_text_extension: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: user.main }

    admin.review:
        class: App\Admin\ReviewAdmin
        arguments: [~, App\Entity\Review, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: review.main }

    admin.game:
        class: App\Admin\GameAdmin
        arguments: [~, App\Entity\Game, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: game.main }
